name: Knip-reporter

on:
  workflow_run:
    workflows: ["Knip"]
    types:
      - completed

jobs:
  knip-reporter:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    uses: ariesgun/.github/.github/workflows/knip-reporter.yml@main
    with:
      workflow-run-id: ${{ github.event.workflow_run.id }}
      workflow: ${{ github.workflow }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
